version: '3.9'
services:
  web-site0:
    image: nginx:latest
    container_name: web-site0
    volumes:
    - ./web-site0:/etc/nginx/html
    ports:
    - 8080:80
    restart: always

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/etc/nginx/html
    depends_on:
      - web-site0
    restart: always
