version: '3.9'
services:

  main:
    image: nginx:latest
    container_name: main
    volumes:
      - ./main:/etc/nginx/html
      - ./nginx-conf/main-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    restart: always

  web-site0:
    image: nginx:latest
    container_name: web-site0
    volumes:
      - ./web-site0:/etc/nginx/html
      - ./nginx-conf/web-site0-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    restart: always

  blog:
    image: node:latest
    container_name: blog
    restart: always
    volumes:
      - ./blog:/home
    working_dir: /home
    ports:
      - 3000:80
    command: bash -c "chmod +x startup.sh && ./startup.sh"

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx-conf/proxy-nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-site0
      - blog
      - main
    restart: always
